  version: '3'
    
  services:
    db:
      image: postgres
      volumes:
        - /usr/app/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: bash -c "sleep 5 && python ./manage.py makemigrations && python ./manage.py migrate --run-syncdb && python ./manage.py runserver 0.0.0.0:80"
      ports:
        - "80:80"
      volumes:
        - .:/code
      depends_on:
        - db
