  version: '3'
    
  services:
    db:
      image: postgres
      volumes:
        - /usr/app/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    pgsql:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@local.com
        - PGADMIN_DEFAULT_PASSWORD=111
      ports:
        - "5050:80"
      volumes:
        - "./servers.json:/pgadmin4/servers.json"
      depends_on:
        - db
    web:
      build: .
      restart: always
      command: bash -c "sleep 5 && python ./manage.py makemigrations && python ./manage.py collectstatic --noinput && python ./manage.py migrate --run-syncdb && uwsgi --ini uwsgi/uwsgi.ini"
      ports:
        - "8080:8080"
      volumes:
        - .:/code
      depends_on:
        - db
    nginx:
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:
        - .:/docker_api
        depends_on:
        - web