# Generated by Django 3.0.5 on 2020-04-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.PositiveSmallIntegerField()),
                ('date_captured', models.DateTimeField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('power', models.FloatField()),
                ('system_load', models.FloatField()),
                ('work_time', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('date_captured',),
            },
        ),
    ]
